- name: Remove existing container
  community.docker.docker_container:
    name: portainer
    state: absent
    purge_networks: true
    force_kill: true
  when: remove_existing_container

- name: Remove persistent data
  community.docker.docker_volume:
    name: portainer-data
    state: absent
  when: remove_persistent_data
