- name: Remove old container and data
  ansible.builtin.include_tasks: clean-up.yml

- name: Deploy potrainer
  ansible.builtin.include_tasks: deploy-container.yml

- name: Create admin account
  ansible.builtin.include_tasks: create-account.yml
  when: admin_user and admin_password is defined and remove_persistent_data
